spring:
  application:
    name: AI Summarizer
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: deepseek/deepseek-r1-0528:free

server:
  port: 8080

api:
  base-path: /api/v1