spring:
  application:
    name: AI Summarizer

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: qwen/qwen3-235b-a22b-2507:free

server:
  port: 8080