spring:
  application:
    name: AI Summarizer

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: deepseek/deepseek-r1-0528:free

server:
  port: 8080