spring:
  application:
    name: AI Summarizer

  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: ${OPENROUTER_AI_MODEL}

server:
  port: 8081

dotenv:
  enabled: true 
  ignore-file-not-found: true
