name: Simple CD

on:
  push:
    branches: [main, master]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images (docker-compose)
        run: docker compose -f docker-compose.yml build

      - name: Push Docker images (docker-compose)
        run: docker compose -f docker-compose.yml push
